// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-8h2LKVHGcXDC5iu9AUWpnZ6P7HB6rME',
    appId: '1:612981118412:web:631bd4ce8e2da547423969',
    messagingSenderId: '612981118412',
    projectId: 'kongsi-fyp-app',
    authDomain: 'kongsi-fyp-app.firebaseapp.com',
    storageBucket: 'kongsi-fyp-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApCYOIxQ805HTD2Wbm7KTK46vMmfHAZgQ',
    appId: '1:612981118412:android:20b80b6c548dcbac423969',
    messagingSenderId: '612981118412',
    projectId: 'kongsi-fyp-app',
    storageBucket: 'kongsi-fyp-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuUNT8OU8DbHucfH5-4gkYPN_bouSqPhI',
    appId: '1:612981118412:ios:5fcfdeafc6c1289e423969',
    messagingSenderId: '612981118412',
    projectId: 'kongsi-fyp-app',
    storageBucket: 'kongsi-fyp-app.appspot.com',
    iosBundleId: 'com.example.kongsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuUNT8OU8DbHucfH5-4gkYPN_bouSqPhI',
    appId: '1:612981118412:ios:9aad2f4d43fe81ce423969',
    messagingSenderId: '612981118412',
    projectId: 'kongsi-fyp-app',
    storageBucket: 'kongsi-fyp-app.appspot.com',
    iosBundleId: 'com.example.kongsi.RunnerTests',
  );
}
